services:
  ros:
    build: .
    container_name: ros_container
    command: tail -f /dev/null
    networks:
      - x11
    volumes:
      - .:/workspace

  novnc:
    image: theasp/novnc:latest
    container_name: novnc_container
    environment:
      - DISPLAY_WIDTH=1280
      - DISPLAY_HEIGHT=720
    ports:
      - "8080:8080"
    networks:
      - x11

networks:
  x11:
